# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb63d0773efe492188a78a6bb4b17a35afd5d9250b9e1d6b051a7fea403d8bd7ecbfbb64f374b053eb55e83d35592d3162141da8a80b1f00f776f3ccba2ccb4a

test:
  secret_key_base: 1ad2da66a9e48c3ebe75e5024d76db345e0f65c817970d34e165112550967e21766b12db0c103979d0a1c2f7b4b56e5fb47064715bc7ef91f732d9484da05987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
